language: android

env:
  matrix:
    - MODULE=placeholder ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - MODULE=placeholder ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-23.0.2                # Build tools version
    - android-23                        # Target SDK version
    - extra-android-support             # Support repo
    - extra-android-m2repository        # Support repo... 2?
    - sys-img-armeabi-v7a-android-14    # Emulator

jdk:
  - oraclejdk8

### Emulator
#before_script:
#  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-audio -no-window &

script:
#  - ./gradlew check -PdisablePreDex --continue --stacktrace
#  - android-wait-for-emulator
#  - adb devices
#  - adb shell settings put global window_animation_scale 0 &
#  - adb shell settings put global transition_animation_scale 0 &
#  - adb shell settings put global animator_duration_scale 0 &
#  - adb shell input keyevent 82 &
#  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
#  - ./gradlew ":$MODULE:build"

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
